channels:
- conda-forge
- bioconda
dependencies:
- bioconda::diamond=2.1.16
- bioconda::pyrodigal-gv=0.3.2
- bioconda::seqkit=2.11.0
- conda-forge::biopython=1.86
- conda-forge::duckdb-cli=1.4.2
- conda-forge::numpy=2.3.4
- conda-forge::openpyxl=3.1.5
- conda-forge::pandas=2.3.3
- conda-forge::polars=1.35.1
- conda-forge::psutil=7.1.3